
spring:
  application:
    name: hw_springboot


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.0.0.12:3306/citi?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: GroupD&Citi

  jackson:
    default-property-inclusion: non_null
logging:
  level:
    root: info

server:
  port: 8088

