
spring:
  application:
    name: hw_springboot
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# 太蠢了，数据库url复制过来没有修改表名，看了一上午!
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/citi_fintech?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

  jackson:
    default-property-inclusion: non_null

server:
  port: 8088

mybatis:
  mapper-locations: classpath:mapper/*.xml